# Generated by Django 4.2.5 on 2023-12-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0003_size_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='count',
        ),
    ]
