# Generated by Django 4.2.5 on 2023-12-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0006_alter_products_imagesone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='size',
            new_name='productsize',
        ),
    ]
