# Generated by Django 4.2.5 on 2023-12-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0007_rename_size_productsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='name',
            new_name='size',
        ),
        migrations.AddField(
            model_name='productsize',
            name='count',
            field=models.PositiveIntegerField(default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='pro_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back_app.products'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductSizeCount',
        ),
    ]
