# Generated by Django 4.2.5 on 2023-12-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0008_rename_name_productsize_size_productsize_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
