# Generated by Django 4.2.5 on 2023-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0009_remove_products_size_alter_productsize_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Trousers', 'Trousers'), ('jeans', 'jeans'), ('shirt', 'shirt'), ('t-shirt', 't-shirt'), ('Shorts', 'Shorts'), ('innerware', 'innerware'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Jackets & Coats', 'Jackets & Coats'), ('Hoodies & Sweatshirts', 'Hoodies & Sweatshirts'), ('Skirts', 'Skirts'), ('tops', 'tops')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids'), ('home', 'home')], max_length=20),
        ),
    ]
