# Generated by Django 4.2.5 on 2023-12-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0010_alter_products_category_alter_products_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=50)),
                ('log_id', models.CharField(max_length=50)),
            ],
        ),
    ]
