# Generated by Django 5.0 on 2023-12-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0013_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('selectedSize', models.CharField(max_length=250)),
                ('product_id', models.CharField(max_length=250)),
                ('log_id', models.CharField(max_length=50)),
            ],
        ),
    ]
