# Generated by Django 5.0 on 2023-12-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
