# Generated by Django 5.0 on 2023-12-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0015_order_order_id_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('placed', 'placed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
