# Generated by Django 5.0 on 2023-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0016_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default=1, upload_to='order_image/'),
            preserve_default=False,
        ),
    ]
