# Generated by Django 5.0 on 2023-12-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0020_alter_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_image/'),
        ),
    ]
