# Generated by Django 5.0 on 2023-12-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0021_alter_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
